version: '3'
services:
  agcl-metered:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: self_metered_agcl
    volumes:
      - ./:/var/www/html/grievance-redressal  # Ensure consistency in paths
      - ./ssl:/etc/ssl
    ports:
      # - "8081:80"  # Site 1 will be accessible on port 8081
      - "443:443"  # Site 1 will be accessible on port 8081

    networks:
      - webcom
      
networks:
  webcom:
    driver: bridge
